apiVersion: apps/v1
kind: Deployment
metadata: 
  name: streaming-deployment
  labels:
    app: streaming-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming-service

  template:
    metadata:
      labels:
        app: streaming-service

    spec:
      containers:
        - name: streaming-service
          image: nsahil992/streaming-service:latest
          ports:
            - containerPort: 8083
