apiVersion: v1
kind: Pod
metadata:
  name: payment-service
  labels:
    app: payment-service
    tier: backend
spec:
  containers:
    - name: payment-service
      image: nsahil992/payment-service:latest
      ports:
      - containerPort: 8082
